// Code generated by protoc-gen-go. DO NOT EDIT.
// source: geographic.proto

package proto_geographic // import "github.com/synerex/proto_geographic"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// geographic data  (mainly for supply)
type Geo struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Id                   int32    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Label                string   `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`
	Data                 []byte   `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	Options              string   `protobuf:"bytes,5,opt,name=options,proto3" json:"options,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Geo) Reset()         { *m = Geo{} }
func (m *Geo) String() string { return proto.CompactTextString(m) }
func (*Geo) ProtoMessage()    {}
func (*Geo) Descriptor() ([]byte, []int) {
	return fileDescriptor_geographic_2d6ebbb98f468642, []int{0}
}
func (m *Geo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Geo.Unmarshal(m, b)
}
func (m *Geo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Geo.Marshal(b, m, deterministic)
}
func (dst *Geo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Geo.Merge(dst, src)
}
func (m *Geo) XXX_Size() int {
	return xxx_messageInfo_Geo.Size(m)
}
func (m *Geo) XXX_DiscardUnknown() {
	xxx_messageInfo_Geo.DiscardUnknown(m)
}

var xxx_messageInfo_Geo proto.InternalMessageInfo

func (m *Geo) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Geo) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Geo) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *Geo) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Geo) GetOptions() string {
	if m != nil {
		return m.Options
	}
	return ""
}

type Line struct {
	From                 []float32 `protobuf:"fixed32,1,rep,packed,name=from,proto3" json:"from,omitempty"`
	To                   []float32 `protobuf:"fixed32,2,rep,packed,name=to,proto3" json:"to,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Line) Reset()         { *m = Line{} }
func (m *Line) String() string { return proto.CompactTextString(m) }
func (*Line) ProtoMessage()    {}
func (*Line) Descriptor() ([]byte, []int) {
	return fileDescriptor_geographic_2d6ebbb98f468642, []int{1}
}
func (m *Line) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Line.Unmarshal(m, b)
}
func (m *Line) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Line.Marshal(b, m, deterministic)
}
func (dst *Line) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Line.Merge(dst, src)
}
func (m *Line) XXX_Size() int {
	return xxx_messageInfo_Line.Size(m)
}
func (m *Line) XXX_DiscardUnknown() {
	xxx_messageInfo_Line.DiscardUnknown(m)
}

var xxx_messageInfo_Line proto.InternalMessageInfo

func (m *Line) GetFrom() []float32 {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *Line) GetTo() []float32 {
	if m != nil {
		return m.To
	}
	return nil
}

type Lines struct {
	Lines                []*Lines `protobuf:"bytes,1,rep,name=lines,proto3" json:"lines,omitempty"`
	Width                int32    `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Color                []int32  `protobuf:"varint,3,rep,packed,name=color,proto3" json:"color,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Lines) Reset()         { *m = Lines{} }
func (m *Lines) String() string { return proto.CompactTextString(m) }
func (*Lines) ProtoMessage()    {}
func (*Lines) Descriptor() ([]byte, []int) {
	return fileDescriptor_geographic_2d6ebbb98f468642, []int{2}
}
func (m *Lines) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Lines.Unmarshal(m, b)
}
func (m *Lines) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Lines.Marshal(b, m, deterministic)
}
func (dst *Lines) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Lines.Merge(dst, src)
}
func (m *Lines) XXX_Size() int {
	return xxx_messageInfo_Lines.Size(m)
}
func (m *Lines) XXX_DiscardUnknown() {
	xxx_messageInfo_Lines.DiscardUnknown(m)
}

var xxx_messageInfo_Lines proto.InternalMessageInfo

func (m *Lines) GetLines() []*Lines {
	if m != nil {
		return m.Lines
	}
	return nil
}

func (m *Lines) GetWidth() int32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *Lines) GetColor() []int32 {
	if m != nil {
		return m.Color
	}
	return nil
}

type Point struct {
	Lat                  float32  `protobuf:"fixed32,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon                  float32  `protobuf:"fixed32,2,opt,name=lon,proto3" json:"lon,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Point) Reset()         { *m = Point{} }
func (m *Point) String() string { return proto.CompactTextString(m) }
func (*Point) ProtoMessage()    {}
func (*Point) Descriptor() ([]byte, []int) {
	return fileDescriptor_geographic_2d6ebbb98f468642, []int{3}
}
func (m *Point) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Point.Unmarshal(m, b)
}
func (m *Point) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Point.Marshal(b, m, deterministic)
}
func (dst *Point) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Point.Merge(dst, src)
}
func (m *Point) XXX_Size() int {
	return xxx_messageInfo_Point.Size(m)
}
func (m *Point) XXX_DiscardUnknown() {
	xxx_messageInfo_Point.DiscardUnknown(m)
}

var xxx_messageInfo_Point proto.InternalMessageInfo

func (m *Point) GetLat() float32 {
	if m != nil {
		return m.Lat
	}
	return 0
}

func (m *Point) GetLon() float32 {
	if m != nil {
		return m.Lon
	}
	return 0
}

type Path struct {
	Points               []*Point `protobuf:"bytes,1,rep,name=points,proto3" json:"points,omitempty"`
	Width                int32    `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Color                []int32  `protobuf:"varint,3,rep,packed,name=color,proto3" json:"color,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Path) Reset()         { *m = Path{} }
func (m *Path) String() string { return proto.CompactTextString(m) }
func (*Path) ProtoMessage()    {}
func (*Path) Descriptor() ([]byte, []int) {
	return fileDescriptor_geographic_2d6ebbb98f468642, []int{4}
}
func (m *Path) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Path.Unmarshal(m, b)
}
func (m *Path) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Path.Marshal(b, m, deterministic)
}
func (dst *Path) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Path.Merge(dst, src)
}
func (m *Path) XXX_Size() int {
	return xxx_messageInfo_Path.Size(m)
}
func (m *Path) XXX_DiscardUnknown() {
	xxx_messageInfo_Path.DiscardUnknown(m)
}

var xxx_messageInfo_Path proto.InternalMessageInfo

func (m *Path) GetPoints() []*Point {
	if m != nil {
		return m.Points
	}
	return nil
}

func (m *Path) GetWidth() int32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *Path) GetColor() []int32 {
	if m != nil {
		return m.Color
	}
	return nil
}

type Paths struct {
	Paths                []*Path  `protobuf:"bytes,1,rep,name=paths,proto3" json:"paths,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Paths) Reset()         { *m = Paths{} }
func (m *Paths) String() string { return proto.CompactTextString(m) }
func (*Paths) ProtoMessage()    {}
func (*Paths) Descriptor() ([]byte, []int) {
	return fileDescriptor_geographic_2d6ebbb98f468642, []int{5}
}
func (m *Paths) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Paths.Unmarshal(m, b)
}
func (m *Paths) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Paths.Marshal(b, m, deterministic)
}
func (dst *Paths) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Paths.Merge(dst, src)
}
func (m *Paths) XXX_Size() int {
	return xxx_messageInfo_Paths.Size(m)
}
func (m *Paths) XXX_DiscardUnknown() {
	xxx_messageInfo_Paths.DiscardUnknown(m)
}

var xxx_messageInfo_Paths proto.InternalMessageInfo

func (m *Paths) GetPaths() []*Path {
	if m != nil {
		return m.Paths
	}
	return nil
}

type Scatter struct {
	Points               []*Point `protobuf:"bytes,1,rep,name=points,proto3" json:"points,omitempty"`
	Radiuses             []int32  `protobuf:"varint,2,rep,packed,name=radiuses,proto3" json:"radiuses,omitempty"`
	Color                []int32  `protobuf:"varint,3,rep,packed,name=color,proto3" json:"color,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Scatter) Reset()         { *m = Scatter{} }
func (m *Scatter) String() string { return proto.CompactTextString(m) }
func (*Scatter) ProtoMessage()    {}
func (*Scatter) Descriptor() ([]byte, []int) {
	return fileDescriptor_geographic_2d6ebbb98f468642, []int{6}
}
func (m *Scatter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Scatter.Unmarshal(m, b)
}
func (m *Scatter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Scatter.Marshal(b, m, deterministic)
}
func (dst *Scatter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Scatter.Merge(dst, src)
}
func (m *Scatter) XXX_Size() int {
	return xxx_messageInfo_Scatter.Size(m)
}
func (m *Scatter) XXX_DiscardUnknown() {
	xxx_messageInfo_Scatter.DiscardUnknown(m)
}

var xxx_messageInfo_Scatter proto.InternalMessageInfo

func (m *Scatter) GetPoints() []*Point {
	if m != nil {
		return m.Points
	}
	return nil
}

func (m *Scatter) GetRadiuses() []int32 {
	if m != nil {
		return m.Radiuses
	}
	return nil
}

func (m *Scatter) GetColor() []int32 {
	if m != nil {
		return m.Color
	}
	return nil
}

func init() {
	proto.RegisterType((*Geo)(nil), "pagent.Geo")
	proto.RegisterType((*Line)(nil), "pagent.Line")
	proto.RegisterType((*Lines)(nil), "pagent.Lines")
	proto.RegisterType((*Point)(nil), "pagent.Point")
	proto.RegisterType((*Path)(nil), "pagent.Path")
	proto.RegisterType((*Paths)(nil), "pagent.Paths")
	proto.RegisterType((*Scatter)(nil), "pagent.Scatter")
}

func init() { proto.RegisterFile("geographic.proto", fileDescriptor_geographic_2d6ebbb98f468642) }

var fileDescriptor_geographic_2d6ebbb98f468642 = []byte{
	// 336 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0x3d, 0x4f, 0xe3, 0x40,
	0x10, 0x95, 0x3f, 0x36, 0xb9, 0x9b, 0xcb, 0x9d, 0xa2, 0xd5, 0x15, 0x2b, 0x2a, 0xcb, 0x51, 0x24,
	0x0b, 0x24, 0x47, 0x82, 0x7f, 0x40, 0x43, 0x43, 0x11, 0x2d, 0x0d, 0xd0, 0xa0, 0xb5, 0xbd, 0xd8,
	0x2b, 0x39, 0x1e, 0xcb, 0x9e, 0x08, 0xf2, 0xef, 0xd1, 0x8e, 0x43, 0x28, 0xa0, 0x80, 0xee, 0xbd,
	0x37, 0x6f, 0x9e, 0x9f, 0x57, 0x03, 0xcb, 0xda, 0x62, 0x3d, 0x98, 0xbe, 0x71, 0x65, 0xde, 0x0f,
	0x48, 0x28, 0x67, 0xbd, 0xa9, 0x6d, 0x47, 0xe9, 0x0e, 0xa2, 0x1b, 0x8b, 0x52, 0x42, 0x4c, 0x87,
	0xde, 0xaa, 0x20, 0x09, 0xb2, 0xdf, 0x9a, 0xb1, 0xfc, 0x07, 0xa1, 0xab, 0x54, 0x98, 0x04, 0x99,
	0xd0, 0xa1, 0xab, 0xe4, 0x7f, 0x10, 0xad, 0x29, 0x6c, 0xab, 0x22, 0x36, 0x4d, 0xc4, 0x6f, 0x56,
	0x86, 0x8c, 0x8a, 0x93, 0x20, 0x5b, 0x68, 0xc6, 0x52, 0xc1, 0x1c, 0x7b, 0x72, 0xd8, 0x8d, 0x4a,
	0xb0, 0xf7, 0x9d, 0xa6, 0xe7, 0x10, 0xdf, 0xba, 0xce, 0xfa, 0xad, 0xe7, 0x01, 0x77, 0x2a, 0x48,
	0xa2, 0x2c, 0xd4, 0x8c, 0xfd, 0xf7, 0x08, 0x55, 0xc8, 0x4a, 0x48, 0x98, 0xde, 0x83, 0xf0, 0xde,
	0x51, 0xae, 0x40, 0xb4, 0x1e, 0xb0, 0xfb, 0xcf, 0xe5, 0xdf, 0x7c, 0xea, 0x9e, 0xf3, 0x54, 0x4f,
	0x33, 0xdf, 0xee, 0xc5, 0x55, 0xd4, 0x1c, 0x0b, 0x4f, 0xc4, 0xab, 0x25, 0xb6, 0x38, 0xa8, 0x28,
	0x89, 0xbc, 0xca, 0x24, 0xbd, 0x00, 0xb1, 0x45, 0xd7, 0x91, 0x5c, 0x42, 0xd4, 0x1a, 0xe2, 0xbf,
	0x0e, 0xb5, 0x87, 0xac, 0x60, 0xc7, 0x21, 0x5e, 0xc1, 0x2e, 0x7d, 0x80, 0x78, 0x6b, 0xa8, 0x91,
	0x6b, 0x98, 0xf5, 0x7e, 0xe9, 0x53, 0x0d, 0x8e, 0xd2, 0xc7, 0xe1, 0x8f, 0x7b, 0x18, 0x6a, 0x46,
	0x99, 0x82, 0xe8, 0x3d, 0x38, 0x46, 0x2f, 0x4e, 0xd1, 0x86, 0x1a, 0x3d, 0x8d, 0xd2, 0x02, 0xe6,
	0x77, 0xa5, 0x21, 0xb2, 0xc3, 0x77, 0xab, 0x9c, 0xc1, 0xaf, 0xc1, 0x54, 0x6e, 0x3f, 0xda, 0x91,
	0x9f, 0x55, 0xe8, 0x13, 0xff, 0xba, 0xd0, 0xf5, 0xfa, 0x71, 0x55, 0x3b, 0x6a, 0xf6, 0x45, 0x5e,
	0xe2, 0x6e, 0x33, 0x1e, 0x3a, 0x3b, 0xd8, 0xd7, 0x0d, 0x5f, 0xcc, 0xd3, 0xc7, 0x09, 0x15, 0x33,
	0x56, 0xae, 0xde, 0x02, 0x00, 0x00, 0xff, 0xff, 0x0a, 0x4d, 0x46, 0xd2, 0x57, 0x02, 0x00, 0x00,
}
