// Code generated by protoc-gen-go. DO NOT EDIT.
// source: geography.proto

package proto_geography // import "github.com/synerex/proto_geography"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// for BarGraph type
type BarColorType int32

const (
	BarColorType_FIXCOLOR BarColorType = 0
	BarColorType_VARCOLOR BarColorType = 1
)

var BarColorType_name = map[int32]string{
	0: "FIXCOLOR",
	1: "VARCOLOR",
}
var BarColorType_value = map[string]int32{
	"FIXCOLOR": 0,
	"VARCOLOR": 1,
}

func (x BarColorType) String() string {
	return proto.EnumName(BarColorType_name, int32(x))
}
func (BarColorType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_geography_d3c634079ac790bb, []int{0}
}

type BarShapeType int32

const (
	BarShapeType_BOX BarShapeType = 0
	BarShapeType_HEX BarShapeType = 1
)

var BarShapeType_name = map[int32]string{
	0: "BOX",
	1: "HEX",
}
var BarShapeType_value = map[string]int32{
	"BOX": 0,
	"HEX": 1,
}

func (x BarShapeType) String() string {
	return proto.EnumName(BarShapeType_name, int32(x))
}
func (BarShapeType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_geography_d3c634079ac790bb, []int{1}
}

// geographic data  (mainly for supply)
type Geo struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Id                   int32    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Label                string   `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`
	Data                 []byte   `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	Options              string   `protobuf:"bytes,5,opt,name=options,proto3" json:"options,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Geo) Reset()         { *m = Geo{} }
func (m *Geo) String() string { return proto.CompactTextString(m) }
func (*Geo) ProtoMessage()    {}
func (*Geo) Descriptor() ([]byte, []int) {
	return fileDescriptor_geography_d3c634079ac790bb, []int{0}
}
func (m *Geo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Geo.Unmarshal(m, b)
}
func (m *Geo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Geo.Marshal(b, m, deterministic)
}
func (dst *Geo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Geo.Merge(dst, src)
}
func (m *Geo) XXX_Size() int {
	return xxx_messageInfo_Geo.Size(m)
}
func (m *Geo) XXX_DiscardUnknown() {
	xxx_messageInfo_Geo.DiscardUnknown(m)
}

var xxx_messageInfo_Geo proto.InternalMessageInfo

func (m *Geo) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Geo) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Geo) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *Geo) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Geo) GetOptions() string {
	if m != nil {
		return m.Options
	}
	return ""
}

type Line struct {
	From                 []float64 `protobuf:"fixed64,1,rep,packed,name=from,proto3" json:"from,omitempty"`
	To                   []float64 `protobuf:"fixed64,2,rep,packed,name=to,proto3" json:"to,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Line) Reset()         { *m = Line{} }
func (m *Line) String() string { return proto.CompactTextString(m) }
func (*Line) ProtoMessage()    {}
func (*Line) Descriptor() ([]byte, []int) {
	return fileDescriptor_geography_d3c634079ac790bb, []int{1}
}
func (m *Line) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Line.Unmarshal(m, b)
}
func (m *Line) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Line.Marshal(b, m, deterministic)
}
func (dst *Line) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Line.Merge(dst, src)
}
func (m *Line) XXX_Size() int {
	return xxx_messageInfo_Line.Size(m)
}
func (m *Line) XXX_DiscardUnknown() {
	xxx_messageInfo_Line.DiscardUnknown(m)
}

var xxx_messageInfo_Line proto.InternalMessageInfo

func (m *Line) GetFrom() []float64 {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *Line) GetTo() []float64 {
	if m != nil {
		return m.To
	}
	return nil
}

type Lines struct {
	Lines                []*Line  `protobuf:"bytes,1,rep,name=lines,proto3" json:"lines,omitempty"`
	Width                int32    `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Color                []int32  `protobuf:"varint,3,rep,packed,name=color,proto3" json:"color,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Lines) Reset()         { *m = Lines{} }
func (m *Lines) String() string { return proto.CompactTextString(m) }
func (*Lines) ProtoMessage()    {}
func (*Lines) Descriptor() ([]byte, []int) {
	return fileDescriptor_geography_d3c634079ac790bb, []int{2}
}
func (m *Lines) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Lines.Unmarshal(m, b)
}
func (m *Lines) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Lines.Marshal(b, m, deterministic)
}
func (dst *Lines) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Lines.Merge(dst, src)
}
func (m *Lines) XXX_Size() int {
	return xxx_messageInfo_Lines.Size(m)
}
func (m *Lines) XXX_DiscardUnknown() {
	xxx_messageInfo_Lines.DiscardUnknown(m)
}

var xxx_messageInfo_Lines proto.InternalMessageInfo

func (m *Lines) GetLines() []*Line {
	if m != nil {
		return m.Lines
	}
	return nil
}

func (m *Lines) GetWidth() int32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *Lines) GetColor() []int32 {
	if m != nil {
		return m.Color
	}
	return nil
}

type Point struct {
	Lat                  float64  `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon                  float64  `protobuf:"fixed64,2,opt,name=lon,proto3" json:"lon,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Point) Reset()         { *m = Point{} }
func (m *Point) String() string { return proto.CompactTextString(m) }
func (*Point) ProtoMessage()    {}
func (*Point) Descriptor() ([]byte, []int) {
	return fileDescriptor_geography_d3c634079ac790bb, []int{3}
}
func (m *Point) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Point.Unmarshal(m, b)
}
func (m *Point) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Point.Marshal(b, m, deterministic)
}
func (dst *Point) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Point.Merge(dst, src)
}
func (m *Point) XXX_Size() int {
	return xxx_messageInfo_Point.Size(m)
}
func (m *Point) XXX_DiscardUnknown() {
	xxx_messageInfo_Point.DiscardUnknown(m)
}

var xxx_messageInfo_Point proto.InternalMessageInfo

func (m *Point) GetLat() float64 {
	if m != nil {
		return m.Lat
	}
	return 0
}

func (m *Point) GetLon() float64 {
	if m != nil {
		return m.Lon
	}
	return 0
}

type Path struct {
	Points               []*Point `protobuf:"bytes,1,rep,name=points,proto3" json:"points,omitempty"`
	Width                int32    `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Color                []int32  `protobuf:"varint,3,rep,packed,name=color,proto3" json:"color,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Path) Reset()         { *m = Path{} }
func (m *Path) String() string { return proto.CompactTextString(m) }
func (*Path) ProtoMessage()    {}
func (*Path) Descriptor() ([]byte, []int) {
	return fileDescriptor_geography_d3c634079ac790bb, []int{4}
}
func (m *Path) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Path.Unmarshal(m, b)
}
func (m *Path) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Path.Marshal(b, m, deterministic)
}
func (dst *Path) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Path.Merge(dst, src)
}
func (m *Path) XXX_Size() int {
	return xxx_messageInfo_Path.Size(m)
}
func (m *Path) XXX_DiscardUnknown() {
	xxx_messageInfo_Path.DiscardUnknown(m)
}

var xxx_messageInfo_Path proto.InternalMessageInfo

func (m *Path) GetPoints() []*Point {
	if m != nil {
		return m.Points
	}
	return nil
}

func (m *Path) GetWidth() int32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *Path) GetColor() []int32 {
	if m != nil {
		return m.Color
	}
	return nil
}

type Paths struct {
	Paths                []*Path  `protobuf:"bytes,1,rep,name=paths,proto3" json:"paths,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Paths) Reset()         { *m = Paths{} }
func (m *Paths) String() string { return proto.CompactTextString(m) }
func (*Paths) ProtoMessage()    {}
func (*Paths) Descriptor() ([]byte, []int) {
	return fileDescriptor_geography_d3c634079ac790bb, []int{5}
}
func (m *Paths) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Paths.Unmarshal(m, b)
}
func (m *Paths) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Paths.Marshal(b, m, deterministic)
}
func (dst *Paths) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Paths.Merge(dst, src)
}
func (m *Paths) XXX_Size() int {
	return xxx_messageInfo_Paths.Size(m)
}
func (m *Paths) XXX_DiscardUnknown() {
	xxx_messageInfo_Paths.DiscardUnknown(m)
}

var xxx_messageInfo_Paths proto.InternalMessageInfo

func (m *Paths) GetPaths() []*Path {
	if m != nil {
		return m.Paths
	}
	return nil
}

type Scatter struct {
	Points               []*Point `protobuf:"bytes,1,rep,name=points,proto3" json:"points,omitempty"`
	Radiuses             []int32  `protobuf:"varint,2,rep,packed,name=radiuses,proto3" json:"radiuses,omitempty"`
	Color                []int32  `protobuf:"varint,3,rep,packed,name=color,proto3" json:"color,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Scatter) Reset()         { *m = Scatter{} }
func (m *Scatter) String() string { return proto.CompactTextString(m) }
func (*Scatter) ProtoMessage()    {}
func (*Scatter) Descriptor() ([]byte, []int) {
	return fileDescriptor_geography_d3c634079ac790bb, []int{6}
}
func (m *Scatter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Scatter.Unmarshal(m, b)
}
func (m *Scatter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Scatter.Marshal(b, m, deterministic)
}
func (dst *Scatter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Scatter.Merge(dst, src)
}
func (m *Scatter) XXX_Size() int {
	return xxx_messageInfo_Scatter.Size(m)
}
func (m *Scatter) XXX_DiscardUnknown() {
	xxx_messageInfo_Scatter.DiscardUnknown(m)
}

var xxx_messageInfo_Scatter proto.InternalMessageInfo

func (m *Scatter) GetPoints() []*Point {
	if m != nil {
		return m.Points
	}
	return nil
}

func (m *Scatter) GetRadiuses() []int32 {
	if m != nil {
		return m.Radiuses
	}
	return nil
}

func (m *Scatter) GetColor() []int32 {
	if m != nil {
		return m.Color
	}
	return nil
}

type ViewState struct {
	Lat                  float64  `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon                  float64  `protobuf:"fixed64,2,opt,name=lon,proto3" json:"lon,omitempty"`
	Zoom                 int32    `protobuf:"varint,3,opt,name=zoom,proto3" json:"zoom,omitempty"`
	Pitch                float64  `protobuf:"fixed64,4,opt,name=pitch,proto3" json:"pitch,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ViewState) Reset()         { *m = ViewState{} }
func (m *ViewState) String() string { return proto.CompactTextString(m) }
func (*ViewState) ProtoMessage()    {}
func (*ViewState) Descriptor() ([]byte, []int) {
	return fileDescriptor_geography_d3c634079ac790bb, []int{7}
}
func (m *ViewState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ViewState.Unmarshal(m, b)
}
func (m *ViewState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ViewState.Marshal(b, m, deterministic)
}
func (dst *ViewState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ViewState.Merge(dst, src)
}
func (m *ViewState) XXX_Size() int {
	return xxx_messageInfo_ViewState.Size(m)
}
func (m *ViewState) XXX_DiscardUnknown() {
	xxx_messageInfo_ViewState.DiscardUnknown(m)
}

var xxx_messageInfo_ViewState proto.InternalMessageInfo

func (m *ViewState) GetLat() float64 {
	if m != nil {
		return m.Lat
	}
	return 0
}

func (m *ViewState) GetLon() float64 {
	if m != nil {
		return m.Lon
	}
	return 0
}

func (m *ViewState) GetZoom() int32 {
	if m != nil {
		return m.Zoom
	}
	return 0
}

func (m *ViewState) GetPitch() float64 {
	if m != nil {
		return m.Pitch
	}
	return 0
}

type Bearing struct {
	Bearing              float64  `protobuf:"fixed64,1,opt,name=bearing,proto3" json:"bearing,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Bearing) Reset()         { *m = Bearing{} }
func (m *Bearing) String() string { return proto.CompactTextString(m) }
func (*Bearing) ProtoMessage()    {}
func (*Bearing) Descriptor() ([]byte, []int) {
	return fileDescriptor_geography_d3c634079ac790bb, []int{8}
}
func (m *Bearing) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bearing.Unmarshal(m, b)
}
func (m *Bearing) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bearing.Marshal(b, m, deterministic)
}
func (dst *Bearing) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bearing.Merge(dst, src)
}
func (m *Bearing) XXX_Size() int {
	return xxx_messageInfo_Bearing.Size(m)
}
func (m *Bearing) XXX_DiscardUnknown() {
	xxx_messageInfo_Bearing.DiscardUnknown(m)
}

var xxx_messageInfo_Bearing proto.InternalMessageInfo

func (m *Bearing) GetBearing() float64 {
	if m != nil {
		return m.Bearing
	}
	return 0
}

type Pitch struct {
	Pitch                float64  `protobuf:"fixed64,1,opt,name=pitch,proto3" json:"pitch,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pitch) Reset()         { *m = Pitch{} }
func (m *Pitch) String() string { return proto.CompactTextString(m) }
func (*Pitch) ProtoMessage()    {}
func (*Pitch) Descriptor() ([]byte, []int) {
	return fileDescriptor_geography_d3c634079ac790bb, []int{9}
}
func (m *Pitch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pitch.Unmarshal(m, b)
}
func (m *Pitch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pitch.Marshal(b, m, deterministic)
}
func (dst *Pitch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pitch.Merge(dst, src)
}
func (m *Pitch) XXX_Size() int {
	return xxx_messageInfo_Pitch.Size(m)
}
func (m *Pitch) XXX_DiscardUnknown() {
	xxx_messageInfo_Pitch.DiscardUnknown(m)
}

var xxx_messageInfo_Pitch proto.InternalMessageInfo

func (m *Pitch) GetPitch() float64 {
	if m != nil {
		return m.Pitch
	}
	return 0
}

type ClearMoves struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClearMoves) Reset()         { *m = ClearMoves{} }
func (m *ClearMoves) String() string { return proto.CompactTextString(m) }
func (*ClearMoves) ProtoMessage()    {}
func (*ClearMoves) Descriptor() ([]byte, []int) {
	return fileDescriptor_geography_d3c634079ac790bb, []int{10}
}
func (m *ClearMoves) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClearMoves.Unmarshal(m, b)
}
func (m *ClearMoves) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClearMoves.Marshal(b, m, deterministic)
}
func (dst *ClearMoves) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClearMoves.Merge(dst, src)
}
func (m *ClearMoves) XXX_Size() int {
	return xxx_messageInfo_ClearMoves.Size(m)
}
func (m *ClearMoves) XXX_DiscardUnknown() {
	xxx_messageInfo_ClearMoves.DiscardUnknown(m)
}

var xxx_messageInfo_ClearMoves proto.InternalMessageInfo

func (m *ClearMoves) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type BarData struct {
	Label                string   `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Color                int32    `protobuf:"varint,3,opt,name=color,proto3" json:"color,omitempty"`
	Value                float64  `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BarData) Reset()         { *m = BarData{} }
func (m *BarData) String() string { return proto.CompactTextString(m) }
func (*BarData) ProtoMessage()    {}
func (*BarData) Descriptor() ([]byte, []int) {
	return fileDescriptor_geography_d3c634079ac790bb, []int{11}
}
func (m *BarData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BarData.Unmarshal(m, b)
}
func (m *BarData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BarData.Marshal(b, m, deterministic)
}
func (dst *BarData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BarData.Merge(dst, src)
}
func (m *BarData) XXX_Size() int {
	return xxx_messageInfo_BarData.Size(m)
}
func (m *BarData) XXX_DiscardUnknown() {
	xxx_messageInfo_BarData.DiscardUnknown(m)
}

var xxx_messageInfo_BarData proto.InternalMessageInfo

func (m *BarData) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *BarData) GetColor() int32 {
	if m != nil {
		return m.Color
	}
	return 0
}

func (m *BarData) GetValue() float64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type BarGraph struct {
	Id                   int32                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Ts                   *timestamp.Timestamp `protobuf:"bytes,2,opt,name=ts,proto3" json:"ts,omitempty"`
	ShapeType            BarShapeType         `protobuf:"varint,3,opt,name=shapeType,proto3,enum=pagent.BarShapeType" json:"shapeType,omitempty"`
	ColorType            BarColorType         `protobuf:"varint,4,opt,name=colorType,proto3,enum=pagent.BarColorType" json:"colorType,omitempty"`
	Color                int32                `protobuf:"varint,5,opt,name=color,proto3" json:"color,omitempty"`
	Lat                  float64              `protobuf:"fixed64,6,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon                  float64              `protobuf:"fixed64,7,opt,name=lon,proto3" json:"lon,omitempty"`
	Width                float64              `protobuf:"fixed64,8,opt,name=width,proto3" json:"width,omitempty"`
	Radius               float64              `protobuf:"fixed64,9,opt,name=radius,proto3" json:"radius,omitempty"`
	Min                  float64              `protobuf:"fixed64,10,opt,name=min,proto3" json:"min,omitempty"`
	Max                  float64              `protobuf:"fixed64,11,opt,name=max,proto3" json:"max,omitempty"`
	AreaColor            int32                `protobuf:"varint,12,opt,name=areaColor,proto3" json:"areaColor,omitempty"`
	BarData              []*BarData           `protobuf:"bytes,13,rep,name=barData,proto3" json:"barData,omitempty"`
	Text                 string               `protobuf:"bytes,14,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *BarGraph) Reset()         { *m = BarGraph{} }
func (m *BarGraph) String() string { return proto.CompactTextString(m) }
func (*BarGraph) ProtoMessage()    {}
func (*BarGraph) Descriptor() ([]byte, []int) {
	return fileDescriptor_geography_d3c634079ac790bb, []int{12}
}
func (m *BarGraph) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BarGraph.Unmarshal(m, b)
}
func (m *BarGraph) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BarGraph.Marshal(b, m, deterministic)
}
func (dst *BarGraph) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BarGraph.Merge(dst, src)
}
func (m *BarGraph) XXX_Size() int {
	return xxx_messageInfo_BarGraph.Size(m)
}
func (m *BarGraph) XXX_DiscardUnknown() {
	xxx_messageInfo_BarGraph.DiscardUnknown(m)
}

var xxx_messageInfo_BarGraph proto.InternalMessageInfo

func (m *BarGraph) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *BarGraph) GetTs() *timestamp.Timestamp {
	if m != nil {
		return m.Ts
	}
	return nil
}

func (m *BarGraph) GetShapeType() BarShapeType {
	if m != nil {
		return m.ShapeType
	}
	return BarShapeType_BOX
}

func (m *BarGraph) GetColorType() BarColorType {
	if m != nil {
		return m.ColorType
	}
	return BarColorType_FIXCOLOR
}

func (m *BarGraph) GetColor() int32 {
	if m != nil {
		return m.Color
	}
	return 0
}

func (m *BarGraph) GetLat() float64 {
	if m != nil {
		return m.Lat
	}
	return 0
}

func (m *BarGraph) GetLon() float64 {
	if m != nil {
		return m.Lon
	}
	return 0
}

func (m *BarGraph) GetWidth() float64 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *BarGraph) GetRadius() float64 {
	if m != nil {
		return m.Radius
	}
	return 0
}

func (m *BarGraph) GetMin() float64 {
	if m != nil {
		return m.Min
	}
	return 0
}

func (m *BarGraph) GetMax() float64 {
	if m != nil {
		return m.Max
	}
	return 0
}

func (m *BarGraph) GetAreaColor() int32 {
	if m != nil {
		return m.AreaColor
	}
	return 0
}

func (m *BarGraph) GetBarData() []*BarData {
	if m != nil {
		return m.BarData
	}
	return nil
}

func (m *BarGraph) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type BarGraphs struct {
	Bars                 []*BarGraph `protobuf:"bytes,1,rep,name=bars,proto3" json:"bars,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *BarGraphs) Reset()         { *m = BarGraphs{} }
func (m *BarGraphs) String() string { return proto.CompactTextString(m) }
func (*BarGraphs) ProtoMessage()    {}
func (*BarGraphs) Descriptor() ([]byte, []int) {
	return fileDescriptor_geography_d3c634079ac790bb, []int{13}
}
func (m *BarGraphs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BarGraphs.Unmarshal(m, b)
}
func (m *BarGraphs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BarGraphs.Marshal(b, m, deterministic)
}
func (dst *BarGraphs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BarGraphs.Merge(dst, src)
}
func (m *BarGraphs) XXX_Size() int {
	return xxx_messageInfo_BarGraphs.Size(m)
}
func (m *BarGraphs) XXX_DiscardUnknown() {
	xxx_messageInfo_BarGraphs.DiscardUnknown(m)
}

var xxx_messageInfo_BarGraphs proto.InternalMessageInfo

func (m *BarGraphs) GetBars() []*BarGraph {
	if m != nil {
		return m.Bars
	}
	return nil
}

func init() {
	proto.RegisterType((*Geo)(nil), "pagent.Geo")
	proto.RegisterType((*Line)(nil), "pagent.Line")
	proto.RegisterType((*Lines)(nil), "pagent.Lines")
	proto.RegisterType((*Point)(nil), "pagent.Point")
	proto.RegisterType((*Path)(nil), "pagent.Path")
	proto.RegisterType((*Paths)(nil), "pagent.Paths")
	proto.RegisterType((*Scatter)(nil), "pagent.Scatter")
	proto.RegisterType((*ViewState)(nil), "pagent.ViewState")
	proto.RegisterType((*Bearing)(nil), "pagent.Bearing")
	proto.RegisterType((*Pitch)(nil), "pagent.Pitch")
	proto.RegisterType((*ClearMoves)(nil), "pagent.ClearMoves")
	proto.RegisterType((*BarData)(nil), "pagent.BarData")
	proto.RegisterType((*BarGraph)(nil), "pagent.BarGraph")
	proto.RegisterType((*BarGraphs)(nil), "pagent.BarGraphs")
	proto.RegisterEnum("pagent.BarColorType", BarColorType_name, BarColorType_value)
	proto.RegisterEnum("pagent.BarShapeType", BarShapeType_name, BarShapeType_value)
}

func init() { proto.RegisterFile("geography.proto", fileDescriptor_geography_d3c634079ac790bb) }

var fileDescriptor_geography_d3c634079ac790bb = []byte{
	// 696 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0xed, 0x4e, 0xdb, 0x4a,
	0x10, 0xc5, 0x71, 0x9c, 0x8f, 0x21, 0x40, 0xb4, 0x42, 0x57, 0x2b, 0x74, 0xaf, 0x6e, 0xe4, 0xd2,
	0x2a, 0x4d, 0xa5, 0xa0, 0xa6, 0x4f, 0xd0, 0xd0, 0x96, 0x56, 0xa5, 0x02, 0x2d, 0x88, 0x42, 0xff,
	0x54, 0xeb, 0x64, 0x71, 0x2c, 0xd9, 0x5e, 0xcb, 0xde, 0x40, 0xe8, 0x8b, 0xf4, 0x75, 0xab, 0x99,
	0xb5, 0x13, 0xab, 0xa8, 0x12, 0xfd, 0x37, 0xe7, 0xcc, 0x87, 0x67, 0x3c, 0x67, 0x16, 0xf6, 0x42,
	0xa5, 0xc3, 0x5c, 0x66, 0x8b, 0x87, 0x71, 0x96, 0x6b, 0xa3, 0x59, 0x2b, 0x93, 0xa1, 0x4a, 0xcd,
	0xc1, 0xff, 0xa1, 0xd6, 0x61, 0xac, 0x8e, 0x88, 0x0d, 0x96, 0xb7, 0x47, 0x26, 0x4a, 0x54, 0x61,
	0x64, 0x92, 0xd9, 0x40, 0x3f, 0x01, 0xf7, 0x44, 0x69, 0xc6, 0xa0, 0x69, 0x1e, 0x32, 0xc5, 0x9d,
	0x81, 0x33, 0xec, 0x0a, 0xb2, 0xd9, 0x2e, 0x34, 0xa2, 0x39, 0x6f, 0x0c, 0x9c, 0xa1, 0x27, 0x1a,
	0xd1, 0x9c, 0xed, 0x83, 0x17, 0xcb, 0x40, 0xc5, 0xdc, 0xa5, 0x20, 0x0b, 0x30, 0x73, 0x2e, 0x8d,
	0xe4, 0xcd, 0x81, 0x33, 0xec, 0x09, 0xb2, 0x19, 0x87, 0xb6, 0xce, 0x4c, 0xa4, 0xd3, 0x82, 0x7b,
	0x14, 0x5b, 0x41, 0x7f, 0x04, 0xcd, 0xd3, 0x28, 0x55, 0x98, 0x75, 0x9b, 0xeb, 0x84, 0x3b, 0x03,
	0x77, 0xe8, 0x08, 0xb2, 0xf1, 0x7b, 0x46, 0xf3, 0x06, 0x31, 0x0d, 0xa3, 0xfd, 0xaf, 0xe0, 0x61,
	0x6c, 0xc1, 0x7c, 0xf0, 0x62, 0x34, 0x28, 0x7a, 0x7b, 0xd2, 0x1b, 0xdb, 0xe1, 0xc6, 0xe8, 0x15,
	0xd6, 0x85, 0xcd, 0xdd, 0x47, 0x73, 0xb3, 0x28, 0xfb, 0xb5, 0x00, 0xd9, 0x99, 0x8e, 0x75, 0xce,
	0xdd, 0x81, 0x8b, 0x2c, 0x01, 0xff, 0x15, 0x78, 0xe7, 0x3a, 0x4a, 0x0d, 0xeb, 0x83, 0x1b, 0x4b,
	0x43, 0x43, 0x3b, 0x02, 0x4d, 0x62, 0x74, 0x4a, 0x45, 0x90, 0xd1, 0xa9, 0x7f, 0x03, 0xcd, 0x73,
	0x69, 0x16, 0xec, 0x39, 0xb4, 0x32, 0x4c, 0xaa, 0xba, 0xd8, 0xa9, 0xba, 0xa0, 0x52, 0xa2, 0x74,
	0xfe, 0x75, 0x1f, 0xd2, 0x2c, 0x68, 0xc0, 0x0c, 0x8d, 0xdf, 0x07, 0x44, 0xaf, 0xb0, 0x2e, 0x3f,
	0x80, 0xf6, 0xc5, 0x4c, 0x1a, 0xa3, 0xf2, 0xa7, 0xb6, 0x72, 0x00, 0x9d, 0x5c, 0xce, 0xa3, 0x65,
	0xa1, 0x0a, 0xfa, 0xab, 0x9e, 0x58, 0xe3, 0x3f, 0x34, 0x74, 0x03, 0xdd, 0xab, 0x48, 0xdd, 0x5f,
	0x18, 0x69, 0xd4, 0x53, 0x7e, 0x0e, 0xae, 0xf1, 0x87, 0xd6, 0x09, 0x29, 0xc2, 0x13, 0x64, 0x63,
	0xe9, 0x2c, 0x32, 0xb3, 0x05, 0x29, 0xc2, 0x11, 0x16, 0xf8, 0xcf, 0xa0, 0x3d, 0x55, 0x32, 0x8f,
	0xd2, 0x10, 0xd5, 0x11, 0x58, 0xb3, 0x2c, 0x5e, 0x41, 0xff, 0x3f, 0xf0, 0xce, 0x31, 0x7a, 0x53,
	0xc3, 0xa9, 0xd7, 0x78, 0x01, 0x70, 0x1c, 0x2b, 0x99, 0x7f, 0xd1, 0x77, 0xaa, 0xc0, 0x32, 0x89,
	0x2a, 0x0a, 0x19, 0x56, 0xaa, 0xad, 0xa0, 0xff, 0x19, 0xda, 0x53, 0x99, 0xbf, 0x43, 0x25, 0xae,
	0x35, 0xeb, 0xd4, 0x35, 0x5b, 0x9b, 0xde, 0x59, 0x4f, 0x8f, 0xec, 0x9d, 0x8c, 0x97, 0xaa, 0x1c,
	0xd0, 0x02, 0xff, 0xa7, 0x0b, 0x9d, 0xa9, 0xcc, 0x4f, 0xf0, 0xba, 0xca, 0x93, 0x70, 0xd6, 0x27,
	0x31, 0x82, 0x86, 0x29, 0x28, 0x7e, 0x7b, 0x72, 0x30, 0xb6, 0xb7, 0x36, 0xae, 0x6e, 0x6d, 0x7c,
	0x59, 0xdd, 0x9a, 0x68, 0x98, 0x82, 0x4d, 0xa0, 0x5b, 0x2c, 0x64, 0xa6, 0x2e, 0xf1, 0xce, 0xf0,
	0xc3, 0xbb, 0x93, 0xfd, 0x6a, 0x71, 0x53, 0x99, 0x5f, 0x54, 0x3e, 0xb1, 0x09, 0xc3, 0x1c, 0xea,
	0x8d, 0x72, 0x9a, 0x8f, 0x72, 0x8e, 0x2b, 0x9f, 0xd8, 0x84, 0x6d, 0x86, 0xf3, 0xea, 0xc3, 0x95,
	0xdb, 0x6c, 0x3d, 0xda, 0x66, 0x7b, 0xb3, 0xcd, 0xb5, 0x76, 0x3b, 0xf6, 0x07, 0x58, 0xed, 0xfe,
	0x03, 0x2d, 0x2b, 0x1b, 0xde, 0x25, 0xba, 0x44, 0x98, 0x9f, 0x44, 0x29, 0x07, 0x9b, 0x9f, 0x44,
	0x29, 0x31, 0x72, 0xc5, 0xb7, 0x4b, 0x46, 0xae, 0xd8, 0xbf, 0xd0, 0x95, 0xb9, 0x92, 0xd4, 0x27,
	0xef, 0x51, 0x3f, 0x1b, 0x82, 0xbd, 0x84, 0x76, 0x60, 0xf7, 0xc4, 0x77, 0x48, 0xc8, 0x7b, 0xb5,
	0xd9, 0x90, 0x16, 0x95, 0x9f, 0xde, 0x27, 0xb5, 0x32, 0x7c, 0xb7, 0x7c, 0x9f, 0xd4, 0xca, 0xf8,
	0xaf, 0xa1, 0x5b, 0x2d, 0xa6, 0x60, 0x87, 0xd0, 0x0c, 0x64, 0x5e, 0x5d, 0x44, 0xbf, 0x56, 0x88,
	0x02, 0x04, 0x79, 0x47, 0x23, 0xe8, 0xd5, 0x7f, 0x1b, 0xeb, 0x41, 0xe7, 0xc3, 0xa7, 0xeb, 0xe3,
	0xb3, 0xd3, 0x33, 0xd1, 0xdf, 0x42, 0x74, 0xf5, 0x56, 0x58, 0xe4, 0x8c, 0x06, 0x14, 0xbb, 0x5e,
	0x0b, 0x6b, 0x83, 0x3b, 0x3d, 0xbb, 0xee, 0x6f, 0xa1, 0xf1, 0xf1, 0xfd, 0x75, 0xdf, 0x99, 0x1e,
	0x7e, 0xf3, 0xc3, 0xc8, 0x2c, 0x96, 0xc1, 0x78, 0xa6, 0x93, 0xa3, 0xe2, 0x21, 0x55, 0xb9, 0x5a,
	0xd9, 0xa7, 0xf6, 0xfb, 0xfa, 0x41, 0x0e, 0x5a, 0x44, 0xbc, 0xf9, 0x15, 0x00, 0x00, 0xff, 0xff,
	0xd4, 0x6f, 0xbb, 0xcf, 0xa4, 0x05, 0x00, 0x00,
}
