// Code generated by protoc-gen-go. DO NOT EDIT.
// source: geography.proto

package proto_geography // import "github.com/synerex/proto_geography"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// geographic data  (mainly for supply)
type Geo struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Id                   int32    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Label                string   `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`
	Data                 []byte   `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	Options              string   `protobuf:"bytes,5,opt,name=options,proto3" json:"options,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Geo) Reset()         { *m = Geo{} }
func (m *Geo) String() string { return proto.CompactTextString(m) }
func (*Geo) ProtoMessage()    {}
func (*Geo) Descriptor() ([]byte, []int) {
	return fileDescriptor_geography_392c0852fe81f422, []int{0}
}
func (m *Geo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Geo.Unmarshal(m, b)
}
func (m *Geo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Geo.Marshal(b, m, deterministic)
}
func (dst *Geo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Geo.Merge(dst, src)
}
func (m *Geo) XXX_Size() int {
	return xxx_messageInfo_Geo.Size(m)
}
func (m *Geo) XXX_DiscardUnknown() {
	xxx_messageInfo_Geo.DiscardUnknown(m)
}

var xxx_messageInfo_Geo proto.InternalMessageInfo

func (m *Geo) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Geo) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Geo) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *Geo) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Geo) GetOptions() string {
	if m != nil {
		return m.Options
	}
	return ""
}

type Line struct {
	From                 []float64 `protobuf:"fixed64,1,rep,packed,name=from,proto3" json:"from,omitempty"`
	To                   []float64 `protobuf:"fixed64,2,rep,packed,name=to,proto3" json:"to,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Line) Reset()         { *m = Line{} }
func (m *Line) String() string { return proto.CompactTextString(m) }
func (*Line) ProtoMessage()    {}
func (*Line) Descriptor() ([]byte, []int) {
	return fileDescriptor_geography_392c0852fe81f422, []int{1}
}
func (m *Line) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Line.Unmarshal(m, b)
}
func (m *Line) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Line.Marshal(b, m, deterministic)
}
func (dst *Line) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Line.Merge(dst, src)
}
func (m *Line) XXX_Size() int {
	return xxx_messageInfo_Line.Size(m)
}
func (m *Line) XXX_DiscardUnknown() {
	xxx_messageInfo_Line.DiscardUnknown(m)
}

var xxx_messageInfo_Line proto.InternalMessageInfo

func (m *Line) GetFrom() []float64 {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *Line) GetTo() []float64 {
	if m != nil {
		return m.To
	}
	return nil
}

type Lines struct {
	Lines                []*Line  `protobuf:"bytes,1,rep,name=lines,proto3" json:"lines,omitempty"`
	Width                int32    `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Color                []int32  `protobuf:"varint,3,rep,packed,name=color,proto3" json:"color,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Lines) Reset()         { *m = Lines{} }
func (m *Lines) String() string { return proto.CompactTextString(m) }
func (*Lines) ProtoMessage()    {}
func (*Lines) Descriptor() ([]byte, []int) {
	return fileDescriptor_geography_392c0852fe81f422, []int{2}
}
func (m *Lines) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Lines.Unmarshal(m, b)
}
func (m *Lines) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Lines.Marshal(b, m, deterministic)
}
func (dst *Lines) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Lines.Merge(dst, src)
}
func (m *Lines) XXX_Size() int {
	return xxx_messageInfo_Lines.Size(m)
}
func (m *Lines) XXX_DiscardUnknown() {
	xxx_messageInfo_Lines.DiscardUnknown(m)
}

var xxx_messageInfo_Lines proto.InternalMessageInfo

func (m *Lines) GetLines() []*Line {
	if m != nil {
		return m.Lines
	}
	return nil
}

func (m *Lines) GetWidth() int32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *Lines) GetColor() []int32 {
	if m != nil {
		return m.Color
	}
	return nil
}

type Point struct {
	Lat                  float64  `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon                  float64  `protobuf:"fixed64,2,opt,name=lon,proto3" json:"lon,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Point) Reset()         { *m = Point{} }
func (m *Point) String() string { return proto.CompactTextString(m) }
func (*Point) ProtoMessage()    {}
func (*Point) Descriptor() ([]byte, []int) {
	return fileDescriptor_geography_392c0852fe81f422, []int{3}
}
func (m *Point) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Point.Unmarshal(m, b)
}
func (m *Point) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Point.Marshal(b, m, deterministic)
}
func (dst *Point) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Point.Merge(dst, src)
}
func (m *Point) XXX_Size() int {
	return xxx_messageInfo_Point.Size(m)
}
func (m *Point) XXX_DiscardUnknown() {
	xxx_messageInfo_Point.DiscardUnknown(m)
}

var xxx_messageInfo_Point proto.InternalMessageInfo

func (m *Point) GetLat() float64 {
	if m != nil {
		return m.Lat
	}
	return 0
}

func (m *Point) GetLon() float64 {
	if m != nil {
		return m.Lon
	}
	return 0
}

type Path struct {
	Points               []*Point `protobuf:"bytes,1,rep,name=points,proto3" json:"points,omitempty"`
	Width                int32    `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Color                []int32  `protobuf:"varint,3,rep,packed,name=color,proto3" json:"color,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Path) Reset()         { *m = Path{} }
func (m *Path) String() string { return proto.CompactTextString(m) }
func (*Path) ProtoMessage()    {}
func (*Path) Descriptor() ([]byte, []int) {
	return fileDescriptor_geography_392c0852fe81f422, []int{4}
}
func (m *Path) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Path.Unmarshal(m, b)
}
func (m *Path) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Path.Marshal(b, m, deterministic)
}
func (dst *Path) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Path.Merge(dst, src)
}
func (m *Path) XXX_Size() int {
	return xxx_messageInfo_Path.Size(m)
}
func (m *Path) XXX_DiscardUnknown() {
	xxx_messageInfo_Path.DiscardUnknown(m)
}

var xxx_messageInfo_Path proto.InternalMessageInfo

func (m *Path) GetPoints() []*Point {
	if m != nil {
		return m.Points
	}
	return nil
}

func (m *Path) GetWidth() int32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *Path) GetColor() []int32 {
	if m != nil {
		return m.Color
	}
	return nil
}

type Paths struct {
	Paths                []*Path  `protobuf:"bytes,1,rep,name=paths,proto3" json:"paths,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Paths) Reset()         { *m = Paths{} }
func (m *Paths) String() string { return proto.CompactTextString(m) }
func (*Paths) ProtoMessage()    {}
func (*Paths) Descriptor() ([]byte, []int) {
	return fileDescriptor_geography_392c0852fe81f422, []int{5}
}
func (m *Paths) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Paths.Unmarshal(m, b)
}
func (m *Paths) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Paths.Marshal(b, m, deterministic)
}
func (dst *Paths) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Paths.Merge(dst, src)
}
func (m *Paths) XXX_Size() int {
	return xxx_messageInfo_Paths.Size(m)
}
func (m *Paths) XXX_DiscardUnknown() {
	xxx_messageInfo_Paths.DiscardUnknown(m)
}

var xxx_messageInfo_Paths proto.InternalMessageInfo

func (m *Paths) GetPaths() []*Path {
	if m != nil {
		return m.Paths
	}
	return nil
}

type Scatter struct {
	Points               []*Point `protobuf:"bytes,1,rep,name=points,proto3" json:"points,omitempty"`
	Radiuses             []int32  `protobuf:"varint,2,rep,packed,name=radiuses,proto3" json:"radiuses,omitempty"`
	Color                []int32  `protobuf:"varint,3,rep,packed,name=color,proto3" json:"color,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Scatter) Reset()         { *m = Scatter{} }
func (m *Scatter) String() string { return proto.CompactTextString(m) }
func (*Scatter) ProtoMessage()    {}
func (*Scatter) Descriptor() ([]byte, []int) {
	return fileDescriptor_geography_392c0852fe81f422, []int{6}
}
func (m *Scatter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Scatter.Unmarshal(m, b)
}
func (m *Scatter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Scatter.Marshal(b, m, deterministic)
}
func (dst *Scatter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Scatter.Merge(dst, src)
}
func (m *Scatter) XXX_Size() int {
	return xxx_messageInfo_Scatter.Size(m)
}
func (m *Scatter) XXX_DiscardUnknown() {
	xxx_messageInfo_Scatter.DiscardUnknown(m)
}

var xxx_messageInfo_Scatter proto.InternalMessageInfo

func (m *Scatter) GetPoints() []*Point {
	if m != nil {
		return m.Points
	}
	return nil
}

func (m *Scatter) GetRadiuses() []int32 {
	if m != nil {
		return m.Radiuses
	}
	return nil
}

func (m *Scatter) GetColor() []int32 {
	if m != nil {
		return m.Color
	}
	return nil
}

type ViewState struct {
	Lat                  float64  `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon                  float64  `protobuf:"fixed64,2,opt,name=lon,proto3" json:"lon,omitempty"`
	Zoom                 int32    `protobuf:"varint,3,opt,name=zoom,proto3" json:"zoom,omitempty"`
	Pitch                float64  `protobuf:"fixed64,4,opt,name=pitch,proto3" json:"pitch,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ViewState) Reset()         { *m = ViewState{} }
func (m *ViewState) String() string { return proto.CompactTextString(m) }
func (*ViewState) ProtoMessage()    {}
func (*ViewState) Descriptor() ([]byte, []int) {
	return fileDescriptor_geography_392c0852fe81f422, []int{7}
}
func (m *ViewState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ViewState.Unmarshal(m, b)
}
func (m *ViewState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ViewState.Marshal(b, m, deterministic)
}
func (dst *ViewState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ViewState.Merge(dst, src)
}
func (m *ViewState) XXX_Size() int {
	return xxx_messageInfo_ViewState.Size(m)
}
func (m *ViewState) XXX_DiscardUnknown() {
	xxx_messageInfo_ViewState.DiscardUnknown(m)
}

var xxx_messageInfo_ViewState proto.InternalMessageInfo

func (m *ViewState) GetLat() float64 {
	if m != nil {
		return m.Lat
	}
	return 0
}

func (m *ViewState) GetLon() float64 {
	if m != nil {
		return m.Lon
	}
	return 0
}

func (m *ViewState) GetZoom() int32 {
	if m != nil {
		return m.Zoom
	}
	return 0
}

func (m *ViewState) GetPitch() float64 {
	if m != nil {
		return m.Pitch
	}
	return 0
}

func init() {
	proto.RegisterType((*Geo)(nil), "pagent.Geo")
	proto.RegisterType((*Line)(nil), "pagent.Line")
	proto.RegisterType((*Lines)(nil), "pagent.Lines")
	proto.RegisterType((*Point)(nil), "pagent.Point")
	proto.RegisterType((*Path)(nil), "pagent.Path")
	proto.RegisterType((*Paths)(nil), "pagent.Paths")
	proto.RegisterType((*Scatter)(nil), "pagent.Scatter")
	proto.RegisterType((*ViewState)(nil), "pagent.ViewState")
}

func init() { proto.RegisterFile("geography.proto", fileDescriptor_geography_392c0852fe81f422) }

var fileDescriptor_geography_392c0852fe81f422 = []byte{
	// 365 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0x4f, 0x6b, 0xd5, 0x40,
	0x10, 0x67, 0x93, 0xb7, 0xaf, 0x76, 0xac, 0x7f, 0x58, 0x3c, 0x2c, 0x9e, 0xc2, 0xa2, 0xf0, 0x50,
	0x48, 0x41, 0xbf, 0x81, 0x17, 0x2f, 0x1e, 0xca, 0x16, 0x94, 0x7a, 0x91, 0x4d, 0xb2, 0x26, 0x0b,
	0x49, 0x66, 0x49, 0xa6, 0xd4, 0xe7, 0xa7, 0x97, 0x99, 0xf4, 0xf5, 0x20, 0x08, 0xf5, 0xf6, 0xfb,
	0x33, 0x33, 0xf9, 0xcd, 0x66, 0xe0, 0x45, 0x1f, 0xb1, 0x5f, 0x42, 0x1e, 0x8e, 0x75, 0x5e, 0x90,
	0xd0, 0xec, 0x73, 0xe8, 0xe3, 0x4c, 0x6e, 0x82, 0xf2, 0x73, 0x44, 0x63, 0x60, 0x47, 0xc7, 0x1c,
	0xad, 0xaa, 0xd4, 0xe1, 0xdc, 0x0b, 0x36, 0xcf, 0xa1, 0x48, 0x9d, 0x2d, 0x2a, 0x75, 0xd0, 0xbe,
	0x48, 0x9d, 0x79, 0x05, 0x7a, 0x0c, 0x4d, 0x1c, 0x6d, 0x29, 0x45, 0x1b, 0xe1, 0xce, 0x2e, 0x50,
	0xb0, 0xbb, 0x4a, 0x1d, 0x2e, 0xbc, 0x60, 0x63, 0xe1, 0x0c, 0x33, 0x25, 0x9c, 0x57, 0xab, 0xa5,
	0xf6, 0x44, 0xdd, 0x3b, 0xd8, 0x7d, 0x49, 0x73, 0xe4, 0xae, 0x9f, 0x0b, 0x4e, 0x56, 0x55, 0xe5,
	0x41, 0x79, 0xc1, 0xfc, 0x3d, 0x42, 0x5b, 0x88, 0x52, 0x10, 0xba, 0x6f, 0xa0, 0xb9, 0x76, 0x35,
	0x0e, 0xf4, 0xc8, 0x40, 0xaa, 0x9f, 0x7e, 0xb8, 0xa8, 0xb7, 0xec, 0x35, 0xbb, 0x7e, 0xb3, 0x38,
	0xdc, 0x5d, 0xea, 0x68, 0xb8, 0xcf, 0xbb, 0x11, 0x56, 0x5b, 0x1c, 0x71, 0xb1, 0x65, 0x55, 0xb2,
	0x2a, 0xc4, 0xbd, 0x07, 0x7d, 0x85, 0x69, 0x26, 0xf3, 0x12, 0xca, 0x31, 0x90, 0x2c, 0xad, 0x3c,
	0x43, 0x51, 0x70, 0x96, 0x21, 0xac, 0xe0, 0xec, 0x6e, 0x60, 0x77, 0x15, 0x68, 0x30, 0x6f, 0x61,
	0x9f, 0xb9, 0xe9, 0x94, 0xe2, 0xd9, 0x29, 0x85, 0x8c, 0xf2, 0xf7, 0xe6, 0x7f, 0xe7, 0x08, 0x34,
	0xc8, 0x82, 0x99, 0xc1, 0xdf, 0x0b, 0xb2, 0xeb, 0x37, 0xcb, 0x35, 0x70, 0x76, 0xdd, 0x06, 0xa2,
	0xb8, 0x3c, 0x36, 0xca, 0x6b, 0x78, 0xb2, 0x84, 0x2e, 0xdd, 0xae, 0x71, 0x95, 0x57, 0xd5, 0xfe,
	0x81, 0xff, 0x23, 0xd0, 0x0d, 0x9c, 0x7f, 0x4d, 0xf1, 0xee, 0x9a, 0x02, 0xc5, 0xc7, 0x3c, 0x0e,
	0xff, 0xc6, 0xdf, 0x88, 0x93, 0x5c, 0x84, 0xf6, 0x82, 0x79, 0x74, 0x4e, 0xd4, 0x0e, 0x72, 0x11,
	0xca, 0x6f, 0xe4, 0xd3, 0x9b, 0xef, 0xae, 0x4f, 0x34, 0xdc, 0x36, 0x75, 0x8b, 0xd3, 0xe5, 0x7a,
	0x9c, 0xe3, 0x12, 0x7f, 0x5d, 0xca, 0x2d, 0xfe, 0x78, 0xb8, 0xcd, 0x66, 0x2f, 0xc2, 0xc7, 0x3f,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x37, 0xa8, 0xee, 0x6b, 0xaf, 0x02, 0x00, 0x00,
}
