// Code generated by protoc-gen-go. DO NOT EDIT.
// source: geographic.proto

package proto_geographic // import "github.com/synerex/proto_geographic"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// geographic data  (mainly for supply)
type Geo struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Id                   int32    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Label                string   `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`
	Data                 []byte   `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	Options              string   `protobuf:"bytes,5,opt,name=options,proto3" json:"options,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Geo) Reset()         { *m = Geo{} }
func (m *Geo) String() string { return proto.CompactTextString(m) }
func (*Geo) ProtoMessage()    {}
func (*Geo) Descriptor() ([]byte, []int) {
	return fileDescriptor_geographic_ab34b3ed1f91c84f, []int{0}
}
func (m *Geo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Geo.Unmarshal(m, b)
}
func (m *Geo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Geo.Marshal(b, m, deterministic)
}
func (dst *Geo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Geo.Merge(dst, src)
}
func (m *Geo) XXX_Size() int {
	return xxx_messageInfo_Geo.Size(m)
}
func (m *Geo) XXX_DiscardUnknown() {
	xxx_messageInfo_Geo.DiscardUnknown(m)
}

var xxx_messageInfo_Geo proto.InternalMessageInfo

func (m *Geo) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Geo) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Geo) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *Geo) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Geo) GetOptions() string {
	if m != nil {
		return m.Options
	}
	return ""
}

type Line struct {
	From                 []float32 `protobuf:"fixed32,1,rep,packed,name=from,proto3" json:"from,omitempty"`
	To                   []float32 `protobuf:"fixed32,2,rep,packed,name=to,proto3" json:"to,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Line) Reset()         { *m = Line{} }
func (m *Line) String() string { return proto.CompactTextString(m) }
func (*Line) ProtoMessage()    {}
func (*Line) Descriptor() ([]byte, []int) {
	return fileDescriptor_geographic_ab34b3ed1f91c84f, []int{1}
}
func (m *Line) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Line.Unmarshal(m, b)
}
func (m *Line) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Line.Marshal(b, m, deterministic)
}
func (dst *Line) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Line.Merge(dst, src)
}
func (m *Line) XXX_Size() int {
	return xxx_messageInfo_Line.Size(m)
}
func (m *Line) XXX_DiscardUnknown() {
	xxx_messageInfo_Line.DiscardUnknown(m)
}

var xxx_messageInfo_Line proto.InternalMessageInfo

func (m *Line) GetFrom() []float32 {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *Line) GetTo() []float32 {
	if m != nil {
		return m.To
	}
	return nil
}

type Lines struct {
	Lines                []*Lines `protobuf:"bytes,1,rep,name=lines,proto3" json:"lines,omitempty"`
	Width                int32    `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Color                []int32  `protobuf:"varint,3,rep,packed,name=color,proto3" json:"color,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Lines) Reset()         { *m = Lines{} }
func (m *Lines) String() string { return proto.CompactTextString(m) }
func (*Lines) ProtoMessage()    {}
func (*Lines) Descriptor() ([]byte, []int) {
	return fileDescriptor_geographic_ab34b3ed1f91c84f, []int{2}
}
func (m *Lines) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Lines.Unmarshal(m, b)
}
func (m *Lines) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Lines.Marshal(b, m, deterministic)
}
func (dst *Lines) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Lines.Merge(dst, src)
}
func (m *Lines) XXX_Size() int {
	return xxx_messageInfo_Lines.Size(m)
}
func (m *Lines) XXX_DiscardUnknown() {
	xxx_messageInfo_Lines.DiscardUnknown(m)
}

var xxx_messageInfo_Lines proto.InternalMessageInfo

func (m *Lines) GetLines() []*Lines {
	if m != nil {
		return m.Lines
	}
	return nil
}

func (m *Lines) GetWidth() int32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *Lines) GetColor() []int32 {
	if m != nil {
		return m.Color
	}
	return nil
}

func init() {
	proto.RegisterType((*Geo)(nil), "pagent.Geo")
	proto.RegisterType((*Line)(nil), "pagent.Line")
	proto.RegisterType((*Lines)(nil), "pagent.Lines")
}

func init() { proto.RegisterFile("geographic.proto", fileDescriptor_geographic_ab34b3ed1f91c84f) }

var fileDescriptor_geographic_ab34b3ed1f91c84f = []byte{
	// 241 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x90, 0x4f, 0x4b, 0xc4, 0x30,
	0x10, 0xc5, 0x49, 0xb2, 0x59, 0x31, 0xfe, 0x41, 0x82, 0x87, 0x1c, 0x43, 0x17, 0xa1, 0x78, 0xe8,
	0x82, 0x7e, 0x03, 0x2f, 0x5e, 0x3c, 0xe5, 0x24, 0x5e, 0x24, 0x6d, 0x63, 0x1b, 0x68, 0x3b, 0x21,
	0x1d, 0xd1, 0xfd, 0xf6, 0x92, 0xa9, 0xe2, 0xed, 0xbd, 0x37, 0xbf, 0x61, 0x1e, 0xa3, 0x6e, 0x86,
	0x00, 0x43, 0xf6, 0x69, 0x8c, 0x5d, 0x93, 0x32, 0x20, 0xe8, 0x7d, 0xf2, 0x43, 0x58, 0xb0, 0x9a,
	0x95, 0x78, 0x0e, 0xa0, 0xb5, 0xda, 0xe1, 0x29, 0x05, 0xc3, 0x2c, 0xab, 0xcf, 0x1d, 0x69, 0x7d,
	0xad, 0x78, 0xec, 0x0d, 0xb7, 0xac, 0x96, 0x8e, 0xc7, 0x5e, 0xdf, 0x2a, 0x39, 0xf9, 0x36, 0x4c,
	0x46, 0x10, 0xb4, 0x99, 0xb2, 0xd9, 0x7b, 0xf4, 0x66, 0x67, 0x59, 0x7d, 0xe9, 0x48, 0x6b, 0xa3,
	0xce, 0x20, 0x61, 0x84, 0x65, 0x35, 0x92, 0xd8, 0x3f, 0x5b, 0xdd, 0xab, 0xdd, 0x4b, 0x5c, 0x42,
	0xd9, 0xfa, 0xc8, 0x30, 0x1b, 0x66, 0x45, 0xcd, 0x1d, 0xe9, 0x72, 0x0f, 0xc1, 0x70, 0x4a, 0x38,
	0x42, 0xf5, 0xaa, 0x64, 0x61, 0x57, 0x7d, 0x50, 0x72, 0x2a, 0x82, 0xe8, 0x8b, 0x87, 0xab, 0x66,
	0xeb, 0xde, 0xd0, 0xd4, 0x6d, 0xb3, 0xd2, 0xee, 0x2b, 0xf6, 0x38, 0xfe, 0x16, 0xde, 0x4c, 0x49,
	0x3b, 0x98, 0x20, 0x1b, 0x61, 0x45, 0x49, 0xc9, 0x3c, 0xdd, 0xbd, 0x1d, 0x86, 0x88, 0xe3, 0x67,
	0xdb, 0x74, 0x30, 0x1f, 0xd7, 0xd3, 0x12, 0x72, 0xf8, 0x3e, 0xd2, 0x63, 0xde, 0xff, 0x3f, 0xd5,
	0xee, 0x29, 0x79, 0xfc, 0x09, 0x00, 0x00, 0xff, 0xff, 0xb3, 0xd1, 0x5d, 0xa7, 0x3e, 0x01, 0x00,
	0x00,
}
